[tool.poetry]
name = "light"
version = "0.1.0"
description = ""
authors = ["Jijun Leng"]
readme = "README.md"

[tool.codespell]
check-filenames = true

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.5.2"
ruamel-yaml = "^0.18.5"

[tool.poetry.group.dev.dependencies]
codespell = "^2.2.6"
mypy = "^1.7.1"
pre-commit = "^3.6.0"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
