# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      taints:
      - key: "app"
        value: "model-group"
        effect: "NoSchedule"
      - key: "model"
        value: "gte-base"
        effect: "NoSchedule"
      kubeletExtraArgs:
        node-labels: "app=model-group,model=gte-base"
